import type { Metadata } from "next";
import { Inter } from 'next/font/google'

// alias import
import { cn } from "@/lib/utils";

import { QueryProvider } from "@/components/query-provider";

// relative import
import "./globals.css";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({
  children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, "antialiased min-h-screen",)}      >
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
